services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
      FLASK_ENV: development
    volumes:
      - .:/code
    depends_on:
      - redis
    command: >
      sh -c "flask db upgrade && flask run.py"

  redis:
    image: redis:alpine
    container_name: roommate_helper_redis
    ports:
      - "6379:6379"
